apiVersion: v1
kind: Service
metadata:
  name: argo-test-service
  labels:
    app: nginx
  namespace: argocd
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx